version: "3"

networks:
  web:
    external: true

services:
  foxcasts-api:
    container_name: foxcasts-api
    image: $DOCKER_IMAGE
    env_file:
      - .env
    labels:
      - traefik.http.routers.foxcasts-api.rule=Host(`${TRAEFIK_HOST}`)
      - traefik.http.routers.foxcasts-api.tls=true
      - traefik.http.routers.foxcasts-api.tls.certresolver=lets-encrypt
      - traefik.port=80
      - traefik.http.services.foxcasts-api.loadbalancer.server.port=${SERVER_PORT}
    networks:
      - web